### ISSUE TITLE
How to make the output colored?

### ISSUE THREAD

**Issue by IonicaBizau** [as-cii/terminal-emojify#2]
I see that your emoticons are colored. What am I doing wrong?

![selection_038](https://cloud.githubusercontent.com/assets/2864371/6819025/fb6f975e-d2c2-11e4-8831-49deb8970b18.png)

**Comment by as-cii** [comment]
@IonicaBizau: thanks for reporting this issue! :bow: 

This gem works by simply converting emoji aliases to raw unicode characters: however, at this point, it's up to your system to render them appropriately.

As far as I know, Ubuntu does not support "colorful" emoji (I think it makes use of `ttf-ancient-fonts`) and therefore they'll be displayed very differently from the Mac version I showed in the screenshot.

Hope this helps! Thank you.
