### ISSUE TITLE
Too many cooks^Wdependencies

### ISSUE THREAD

**Issue by indirect** [as-cii/terminal-emojify#3]
When I ran `gem install terminal-emojify`, a huge number of gems that have nothing to do with emoji were installed, like:
- minitest (this should be a dev dep, so it's not installed by end users)
- nokogiri (what HTML or XML are you parsing? :open_mouth:)
- thread_safe (you're using thread-safe data structures?)
- tzinfo (worldwide time zone information?)
- i18n (internationalization for emoji would be cool, but afaict that's not happening)
- rack (does this include a webapp?)
- loofah (are you html escaping the terminal output?)
- actionview (uhhh....)
- rails-deprecated_sanitizer (???)
- rails-dom-testing (???)

Please make this gem easy to install, since it does something small and sweet!

**Comment by as-cii** [comment]
Hi @indirect, thanks for reporting this issue :bow: 

Actually, I find it quite interesting and I am really surprised about this behavior. The `Gemfile.lock` shows only `gemoji` as a dependency:

```
PATH
  remote: .
  specs:
    terminal-emojify (0.0.1)
      gemoji (~> 2.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    gemoji (2.1.0)
    rake (10.4.2)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (~> 1.7)
  rake (~> 10.0)
  terminal-emojify!
```

![gem_graph](https://cloud.githubusercontent.com/assets/482957/6885362/5e8bda0c-d61d-11e4-87f0-ab786123c317.png)

I have also tried to install the gem in a clean environment. Running `gem list` afterwards shows none of the gems you're reporting:

```
*** LOCAL GEMS ***

bigdecimal (1.2.6)
gemoji (2.1.0)
io-console (0.4.3)
json (1.8.1)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
terminal-emojify (0.0.1)
```

This gems uses `gemoji` under the hood, but I cannot find any related gem [even there](https://github.com/github/gemoji/blob/master/Gemfile). 

Could you confirm this happens also in a clean environment? Thanks again :sparkles:

**Comment by indirect** [comment]
:open_mouth: I seem to have run `gem install terminal emojify` instead of `gem install terminal-emojify`. It's the `emojify` gem that has all these strange dependencies.

I re-ran `gem install terminal-emojify` and everything worked perfectly. So sorry to make you do so much work to double-check!

**Comment by as-cii** [comment]
> I seem to have run gem install terminal emojify instead of gem install terminal-emojify. It's the emojify gem that has all these strange dependencies.

Yeah, I have to admit this gem's name is a bit unfortunate :confused: I wanted to call it `emojify`, but as you're pointing out another gem with this name already exists.

> I re-ran gem install terminal-emojify and everything worked perfectly. So sorry to make you do so much work to double-check!

No problem at all! I hope you find it useful :wink:
